### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by storybegin** [gaowanliang/LightUploader#14]
文件小于4MB，进入小文件通道，上传中
2021/12/19 10:33:50 无法还原 :EOF
panic: 无法还原 :EOF

goroutine 16 [running]:
log.Panicf(0xc00027fa40, 0x10, 0xc000075a20, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:358 +0xc7
main/api/restore/upload.(*RestoreService).SimpleUploadToOriginalLoc(0xc000006580, 0xc00001db00, 0x24, 0xc0000c2000, 0x760, 0xab4969, 0x7, 0xc000018140, 0xd, 0xc000283a10, ...)
        D:/program_data/go/LightUploader/api/restore/upload/onedriveRestore.go:112 +0xafe
main.restore.func1(0xc000296770, 0xc00004d680, 0xc0002cbd30, 0xc0002ea840, 0xc000283bc0, 0xe, 0xc000283bce, 0x24, 0xc00027fe00, 0x18, ...)
        D:/program_data/go/LightUploader/main.go:131 +0x559
created by main.restore
        D:/program_data/go/LightUploader/main.go:110 +0x245

文件以时间命名只有中文和数字
大小为7.67 MB (8,049,325 字节) 
只有这一个出错了
而且文件大于4m

**Comment by gaowanliang** [comment]
可能是文件本身有问题，我这里很难复现

**Comment by storybegin** [comment]
> 可能是文件本身有问题，我这里很难复现

我又出了新的问题
panic: runtime error: slice bounds out of range [6:5]

goroutine 16 [running]:
main.main.func1({0x826ec0, 0x5})
        D:/program_data/go/LightUploader/main.go:355 +0x188
main.restore.func1.2({0x826ec0, 0x5})
        D:/program_data/go/LightUploader/main.go:133 +0x45
main.restore.func1({0xc000269000, 0xe}, {0xc0000065a8, {0x826ccc, 0x0}})
        D:/program_data/go/LightUploader/main.go:152 +0x645
created by main.restore
        D:/program_data/go/LightUploader/main.go:121 +0x7e5

使用202版本会出现  我换201就没有问题

**Comment by gaowanliang** [comment]
> 我又出了新的问题 panic: runtime error: slice bounds out of range [6:5]
> 
> goroutine 16 [running]: main.main.func1({0x826ec0, 0x5}) D:/program_data/go/LightUploader/main.go:355 +0x188 main.restore.func1.2({0x826ec0, 0x5}) D:/program_data/go/LightUploader/main.go:133 +0x45 main.restore.func1({0xc000269000, 0xe}, {0xc0000065a8, {0x826ccc, 0x0}}) D:/program_data/go/LightUploader/main.go:152 +0x645 created by main.restore D:/program_data/go/LightUploader/main.go:121 +0x7e5
> 
> 使用202版本会出现 我换201就没有问题

最新版本已修复

**Comment by storybegin** [comment]
> > 我又出了新的问题 panic: runtime error: slice bounds out of range [6:5]
> > goroutine 16 [running]: main.main.func1({0x826ec0, 0x5}) D:/program_data/go/LightUploader/main.go:355 +0x188 main.restore.func1.2({0x826ec0, 0x5}) D:/program_data/go/LightUploader/main.go:133 +0x45 main.restore.func1({0xc000269000, 0xe}, {0xc0000065a8, {0x826ccc, 0x0}}) D:/program_data/go/LightUploader/main.go:152 +0x645 created by main.restore D:/program_data/go/LightUploader/main.go:121 +0x7e5
> > 使用202版本会出现 我换201就没有问题
> 
> 最新版本已修复

2022/02/10 09:47:07 EOF
panic: EOF


goroutine 11 [running]:
log.Panicln({0xc000451260, 0x3, 0xc0000ca000})
        D:/program_app/go/src/log/log.go:368 +0x65
main/graph/net/http.refreshAccessToken({0xc0002f2920, 0xe}, 0x3, 0xa, {0xc0002f2212, 0x5}, 0x3c, {0x0, 0x0}, {0x0, ...})
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:214 +0x1e5
main/graph/net/http.GetBearer(...)
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:127
main/api/restore/upload.(*RestoreService).recoverableUpload(0x1, {0xc00042c0c0, 0xe6689a}, {0xc0003e0800, 0xc0003ef8f8}, {0x11794d3, 0x1010000012232a0}, {0xc00001e108, 0xc0003ef8b8}, {0xc0003d68d4, ...}, ...)
        D:/program_data/go/LightUploader/api/restore/upload/onedriveRecoverableRestore.go:78 +0x12ce
main/api/restore/upload.(*RestoreService).SimpleUploadToOriginalLoc(0xc000006a88, {0xc00042c0c0, 0x24}, {0xc0003e0800, 0x762}, {0x11794d3, 0x0}, {0xc00001e108, 0x11}, {0xc0003d68d4, ...}, ...)
        D:/program_data/go/LightUploader/api/restore/upload/onedriveRestore.go:73 +0x25d
main.restore.func1({0xc0003d68d4, 0x24}, {0xc000006a90, {0x1176be6, 0x0}})
        D:/program_data/go/LightUploader/main.go:142 +0x5c5
created by main.restore
        D:/program_data/go/LightUploader/main.go:121 +0x7e5

这个是什么问题呢  第一遍我的脚本调用上传的报错 错误信息我没保存
上面的错误信息我第一次手动上传的报错  第二次上传文件上传成功了

**Comment by storybegin** [comment]
panic: EOF


goroutine 1 [running]:
log.Panicln({0xc00025fc28, 0x3, 0xc0001d3000})
        D:/program_app/go/src/log/log.go:368 +0x65
main.main()
        D:/program_data/go/LightUploader/main.go:309 +0x673
突然不能用了  上传什么都提示这个

**Comment by gaowanliang** [comment]
今天偶然触发了这个问题，由于授权文件读写没加锁导致，这个错误确实有点愚蠢了
