### ISSUE TITLE
无法上传整个文件夹

### ISSUE THREAD

**Issue by dongzi0712** [gaowanliang/LightUploader#18]
panic: runtime error: slice bounds out of range [6:5]

goroutine 43 [running]:
main.main.func1({0x95ced6, 0x5})
	D:/program_data/go/LightUploader/main.go:355 +0x188
main.restore.func1.2({0x95ced6, 0x5})
	D:/program_data/go/LightUploader/main.go:133 +0x45
main.restore.func1({0xc000330e40, 0xb1}, {0xc00000e5c0, {0x95cce7, 0xd9e52226927933fa}})
	D:/program_data/go/LightUploader/main.go:152 +0x645
created by main.restore
	D:/program_data/go/LightUploader/main.go:121 +0x80f

**Comment by hope140** [comment]
上传整个文件夹，遇到类似报错，最后显示如下：
```2022/01/27 23:35:26 EOF
panic: EOF


goroutine 5683 [running]:
log.Panicln({0xc000a81a10, 0x3, 0xc000840380})
        D:/program_app/go/src/log/log.go:368 +0x65
main/graph/net/http.refreshAccessToken({0xc00013abc0, 0x31}, 0x3, 0xa, {0xc0002aa1d2, 0x5}, 0x3c, {0x0, 0x0}, {0x0, ...})
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:214 +0x1e5
main/graph/net/http.GetMyIDAndBearer({0xc00013abc0, 0x31}, 0x3, 0xa, {0xc0002aa1d2, 0x5}, 0x3c, {0x0, 0x0}, {0x0, ...})
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:102 +0x25c
main.restore.func1({0xc00001cd20, 0x44}, {0xc000308308, {0x9f6ccc, 0x0}})
        D:/program_data/go/LightUploader/main.go:140 +0x4c5
created by main.restore
        D:/program_data/go/LightUploader/main.go:121 +0x7e5```
