### ISSUE TITLE
GD初始化报错

### ISSUE THREAD

**Issue by madlaxcb** [gaowanliang/LightUploader#3]
```
root@ecs-FalW8:~# LightUploader -v 3
panic: message "googleDriveGetAccess" not found in language "en"

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc0004673a0, 0xc0003afd78, 0x2, 0x2)
        D:/program_data/go/LightUploader/vendor/github.com/nicksnyder/go-i18n/v2/i18n/localizer.go:211 +0x79
main.(*Loc).print(...)
        D:/program_data/go/LightUploader/i18n.go:136
main.main()
        D:/program_data/go/LightUploader/main.go:392 +0x766
```

https://imglink.win/image/2021/04/29/wnOn7.png

**Comment by gaowanliang** [comment]
语言包是联网下载的，因为我程序里为了防止在国内使用github下载语言包失败的情况，用的是jsdelivr，因为jsdelivr要24小时才能缓存过去，所以需要手动下载一下语言包，在放软件的根目录就可以找到.toml，这是语言包，可以直接去github上找文件替换一下，具体位置在源码的i18n文件夹内，去github上下载一下就行。
不过要注意一下，因为Google drive我目前没找到方法分块上传，所以说目前上传的话要先把当前上传资源加载到内存中，如果说这个文件太大就不要传了，等到我找到分块上传方法之后再说。
