### ISSUE TITLE
Failed to upload for the first time

### ISSUE THREAD

**Issue by PS0123456** [gaowanliang/LightUploader#9]
2021/05/17 16:15:32 Failed to Load Files from source :Put "https://xx/_api/v2.0/drive/items/xxxEV6KFEJCV7VOWHISMH5/uploadSession?guid='690daea6-xxx-xxx-9708-8a5c11196f8c'&path='~tmp86_Unforgiven.1992.mkv'&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvY2VsbG9mbWVkaWNpbmUtbXkuc2hhcmVwb2ludC5jb21AMzIyNjJhN2YtODk4ZS00YmE3LTllOTYtMjgyOTc5YTYxNGM0IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmxxTYyMTIzNjk4MiIsImV4cCI6IjE2MjEzMjMzODIiLCJlbmRwb2ludHVybCI6IngyQ2xnb2ZpWmRtaERkd3RmWkZLNHVha0VWTjZ4TTdnZm0wV3U4SFdYbms9IxxxpbnR1cmxMZW5ndGgiOiIzMTIiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IllXRm1PV001WVRVdE1XTTBPUzAwTjJJeExXRmtOVFl0TVRnNFlURTROV1ptTURaaiIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJOek14Wm1FeFpXRXRNall6T1MwME5UZGpMV0V5T0RrdE9USXhNV0l4WmpVeU9XVmkiLCJhcHBfZGlzcGxheW5hbWUiOiJEb3dubG9hZEJvdCIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6ImFkNWU2NWZkLTg1NmQtNDM1Ni1hZWZjLTUzN2E5xxxRpZCI6IjMyMjYyYTdmLTg5OGUtNGJxxxMjk3OWE2MTRjNCIsInVwbiI6InQ1QGNlbGxvZm1lZGljaW5lLm9ubWljcm9zb2Z0LmNvbSIsInB1aWQiOiIxMDAzMjAwMDRCM0FFMkQ2IiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDA0YjNhZTJkNkBsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLndyaXRlIGFsbHByb2ZpbGVzLnJlYWQiLCJhY3JzIjoicjEscjIscjMsYzEsYzIsYzMiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.ZWl4Z3hYaHlCZUFhVEc3ODVsdCtRbDY1VkZybUhZL29VYmZwamVjN0RSND0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)  

PS: Big data approach.

**Comment by gaowanliang** [comment]
正常的超时问题，重新传一下就好了，后面可能会上线断点续传，具体看我有没有时间

**Comment by PS0123456** [comment]
> 正常的超时问题，重新传一下就好了，后面可能会上线断点续传，具体看我有没有时间

我已经尝试第三次了，还是这样。。。。
有个问题是这样的，比如2线程上传，当中有一个尝试超过8次？然后整个上传就取消了。。。
另外，超时原因除了设备与MS之间网络的原因，还有什么因素？ 我以前一直用Oneuploader的，几乎没出现过这种情况（有过1次，但重新上传也能解决。此处并无任何贬低的意思，就是询问下。你这API与OP是一样的吗？

**Comment by gaowanliang** [comment]
一样的，具体OneDrive就提供了一种API。
有bug很正常，我们写程序的都习惯了，毕竟这个程序现在也只是勉强可用，还赶不上萌咖的那个稳定，但是至少是开源的，用着放心。至于超时问题，我曾经遇到过一种情况，也是一个文件怎么传都传不上去，这个文件大小40G，大概放在一个硬盘44G的机器上，这个时候最后一个区块怎么传都传不上去，由于我现在忙于考研，这个东西是忙里偷闲做出来的，这个bug就一直没检查和处理，如果你也是这种情况，我就标记一下，等我在有空去处理的时候首先处理一下。

**Comment by PS0123456** [comment]
> 一样的，具体OneDrive就提供了一种API。
> 有bug很正常，我们写程序的都习惯了，毕竟这个程序现在也只是勉强可用，还赶不上萌咖的那个稳定，但是至少是开源的，用着放心。至于超时问题，我曾经遇到过一种情况，也是一个文件怎么传都传不上去，这个文件大小40G，大概放在一个硬盘44G的机器上，这个时候最后一个区块怎么传都传不上去，由于我现在忙于考研，这个东西是忙里偷闲做出来的，这个bug就一直没检查和处理，如果你也是这种情况，我就标记一下，等我在有空去处理的时候首先处理一下。

对，情况差不多，一个是文件夹，大小100G+，一个36G。考研重要，你有时间看看吧

**Comment by PS0123456** [comment]
@gaowanliang 有时间来看看项目吧，再反馈个待优化项目，一个文件夹下剧集，能不能按照文件名顺序上传，比如第一集、第二集先上传，而不是像现在一样随机上传。这样可以在等待中先看起来。。。

**Comment by gaowanliang** [comment]
我大猜到是什么情况了，这里先记录一下，等考研结束之后去修复一下，大概问题就是文件太大，上传时间过长，导致token超时（token有效期为10分钟，上传同一个文件用同一个token，但是在多文件上传中每上传一个文件都会新申请一个token），不难解决，但是现在确实是没时间，今天突然想到了，来这里记录一下

**Comment by PS0123456** [comment]
> 我大猜到是什么情况了，这里先记录一下，等考研结束之后去修复一下，大概问题就是文件太大，上传时间过长，导致token超时（token有效期为10分钟，上传同一个文件用同一个token，但是在多文件上传中每上传一个文件都会新申请一个token），不难解决，但是现在确实是没时间，今天突然想到了，来这里记录一下

預祝大佬考研成功上岸!
還請有時間修復這個問題和管理員批准問題，謝謝

**Comment by gaowanliang** [comment]
> @gaowanliang 有时间来看看项目吧，再反馈个待优化项目，一个文件夹下剧集，能不能按照文件名顺序上传，比如第一集、第二集先上传，而不是像现在一样随机上传。这样可以在等待中先看起来。。。

测试了一下，如果文件名是纯中文的，则很难做到，毕竟Windows都没做到。如果是阿拉伯数字，且在Windows下按名称是正常排列的，则本程序将在下个更新中支持按序排列并上传。

**Comment by PS0123456** [comment]
> > @gaowanliang 有时间来看看项目吧，再反馈个待优化项目，一个文件夹下剧集，能不能按照文件名顺序上传，比如第一集、第二集先上传，而不是像现在一样随机上传。这样可以在等待中先看起来。。。
> 
> 测试了一下，如果文件名是纯中文的，则很难做到，毕竟Windows都没做到。如果是阿拉伯数字，且在Windows下按名称是正常排列的，则本程序将在下个更新中支持按序排列并上传。

终于盼到你回归了，阿拉伯数字即可。
期待解决需要管理员授权问题。

**Comment by PS0123456** [comment]
panic: runtime error: slice bounds out of range [6:5]

goroutine 15 [running]:
main.main.func1({0x55d83d, 0x5})
        D:/program_data/go/LightUploader/main.go:355 +0x1d8
main.restore.func1.2({0x55d83d, 0x5})
        D:/program_data/go/LightUploader/main.go:133 +0x54
main.restore.func1(0x4000274a30, 0x40004724e0, 0x4000435f30, 0x4000204000, {0x400025de00, 0x9d}, {0x400025de9d, 0x21}, {0x4000024768, 0x16}, ...)
        D:/program_data/go/LightUploader/main.go:152 +0x4e0
created by main.restore
        D:/program_data/go/LightUploader/main.go:121 +0x614
